#!/usr/bin/env bash
#displays 'Best School' 10 times and a hi after the 9th iteration

count="0"
while [ $count -lt 10 ]
do
    echo "Best School"
    if ((count == 8))
    then
        echo "Hi"
    fi
    ((count++))
done
